### ISSUE TITLE
User gets created on invalid passport attribute.

### ISSUE THREAD

**Issue by Fahrradflucht** [jaumard/trailpack-passport#44] opened 2016-05-29 14:41 UTC
If the request fails a validation on a passport attr. (e.g. minLength on password), then the user gets created anyway.

**Comment by Fahrradflucht** [comment] 2016-05-29 14:52
Sorry I named the `passports` attribute on the user model `passport` and that caused the error.

**Comment by Fahrradflucht** [comment] 2016-06-02 08:57
Sorry but I think I have to reopen this again.

I don't no what changed and I didn't have VC from the begining to track down all changes in the project since I'm just dabbling around, but I'm again in the situation where the users get created and just don't have a Passport if the password is to short. I'm not sure if I did something that introduced that again (I updated trails for example) or if my test that it was fixed 4 days ago was wrong.

**Comment by jaumard** [comment] 2016-06-02 11:25
You're right User get created first and then the passport but nothing is done when passport was failing (context https://github.com/jaumard/trailpack-passport/blob/master/api/services/PassportService.js#L118)

**Comment by gliwka** [comment] 2016-10-24 11:34
We would need SQL Transactions for this, since they should always be inserted into the database together. Transactions exist in sequelize, but not all waterline-adapters trails is using have support for them.

**Comment by jaumard** [comment] 2016-10-24 11:48
The problem is if we want to support traikpack-mongoose (and we will) we can't use transactions :( I was thinking of just delete the user it the passport fail...

**Comment by Fahrradflucht** [comment] 2016-10-24 11:54
Yeah either this or using transactions if they are available and delete the user if they are not.

I think it would be nice if the lib could provide the level of data consistency that a user would expect from the datastore technology she/he used...

**Comment by jaumard** [comment] 2016-11-13 13:25
Fixed on v1.0.0 for now I delete manually the user until footprint trailpack allow transaction usage

**Closed by jaumard** 2016-11-13 13:25 UTC
Labels: bug, hacktoberfest
